run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
linters:
  disable-all: true
  enable:
    # Base linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - typecheck     # Type checking
    - unused        # Check for unused constants, variables, functions and types
    
    # Code quality
    - dupl          # Check for code duplication
    - gocyclo       # Check cyclomatic complexity
    - goconst       # Find repeated strings that could be constants
    - prealloc      # Find slice declarations that could potentially be preallocated
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Check for unused function parameters
    
    # Style and formatting
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import statements are formatted according to the 'goimport' command
    - revive        # Drop-in replacement of golint
    - misspell      # Find commonly misspelled English words
    
    # Security
    - gosec         # Security-focused linter
    
    # Performance
    - exportloopref # Check for pointers to enclosing loop variables
    
    # Testing
    - ginkgolinter  # Enforce standards of using ginkgo and gomega
    - testpackage   # Make sure that separate _test packages are used
    
    # Kubernetes/Cloud Native specific
    - nakedret      # Find naked returns in functions greater than a specified function length
    - lll           # Reports long lines
    
    # Additional quality linters
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues
    - gocognit      # Compute and check the cognitive complexity of functions
    - nestif        # Reports deeply nested if statements
    - goerr113      # Check the errors handling expressions
    - nolintlint    # Reports ill-formed or insufficient nolint directives
    - whitespace    # Detection of leading and trailing whitespace
    - wsl           # Add or remove empty lines

linters-settings:
  revive:
    rules:
      - name: comment-spacings
      - name: exported-function
      - name: exported-type
      - name: package-comments
      - name: var-naming
      - name: function-result-limit
        arguments: [3]
      - name: argument-limit
        arguments: [8]
      - name: cyclomatic
        arguments: [15]
      - name: max-public-structs
        arguments: [10]
  
  gocyclo:
    min-complexity: 15
  
  gocognit:
    min-complexity: 20
  
  lll:
    line-length: 120
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - wrapperFunc
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - singleCaseSwitch
  
  gosec:
    excludes:
      - G104 # Audit errors not checked
    config:
      global:
        nosec: true
        audit: enabled
  
  nakedret:
    max-func-lines: 30
  
  nestif:
    min-complexity: 4
  
  unparam:
    check-exported: false
  
  unused:
    check-exported: false
  
  whitespace:
    multi-if: false
    multi-func: false
