apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: simple-test
  namespace: default
spec:
  # Neo4j Enterprise Edition
  edition: enterprise

  # Neo4j Docker image configuration
  image:
    repo: neo4j
    tag: "5.26-enterprise"
    pullPolicy: IfNotPresent

  # Single-node cluster for testing
  topology:
    primaries: 1
    secondaries: 0

  # Storage configuration
  storage:
    className: standard
    size: "5Gi"

  # Resource allocation - increased as recommended
  resources:
    requests:
      memory: "4Gi"
      cpu: "500m"
    limits:
      memory: "8Gi"
      cpu: "2"

  # TLS Configuration
  tls:
    mode: cert-manager
    issuerRef:
      name: ca-cluster-issuer
      kind: ClusterIssuer

  # Required environment variables
  env:
    - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: "yes"

  # Basic Neo4j configuration
  config:
    dbms.logs.query.enabled: "INFO"
    dbms.transaction.timeout: "60s"
