apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: test-cluster
  namespace: default
spec:
  # Neo4j Enterprise Edition
  edition: enterprise

  # Neo4j Docker image configuration
  image:
    repo: neo4j
    tag: "5.26-enterprise"
    pullPolicy: IfNotPresent

  # Three-node cluster topology for high availability
  topology:
    primaries: 3      # 3 primaries for quorum
    secondaries: 3    # Scale to 3 secondaries

  # Storage configuration
  storage:
    className: standard
    size: "10Gi"

  # Resource allocation
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2"

  # TLS with cert-manager
  tls:
    mode: cert-manager
    issuerRef:
      name: ca-cluster-issuer
      kind: ClusterIssuer

  # Service configuration
  service:
    type: ClusterIP

  # Required environment variables
  env:
    - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: "yes"

  # Neo4j configuration
  config:
    dbms.logs.query.enabled: "INFO"
    dbms.transaction.timeout: "60s"
    metrics.enabled: "true"
