apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: test-simple
  namespace: neo4j-dev
spec:
  image:
    repo: neo4j
    tag: "5.26.0-enterprise"
  topology:
    primaries: 1
    secondaries: 0
  storage:
    className: "standard"
    size: "5Gi"
  tls:
    mode: disabled
