# Minimaler Neo4j Enterprise Cluster für OpenShift
# Verwendet 3 Server-Nodes mit Standard-Ressourcen
apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: neo4j-cluster
  namespace: neo4j-cluster
spec:
  # Neo4j Enterprise Image
  image:
    repo: neo4j
    tag: "5.26-enterprise"
    pullPolicy: IfNotPresent

  # Cluster Topology - 3 Server Nodes
  topology:
    servers: 3
    
  # Ressourcen pro Node
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  # Persistenter Storage
  storage:
    className: "lvms-vg1"  # Standard StorageClass für OpenShift
    size: "10Gi"

  # Authentifizierung
  auth:
    provider: native
    adminSecret: neo4j-auth

  # OpenShift-kompatibler Security Context
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  # TLS Konfiguration (optional)
  # tls:
  #   mode: cert-manager
  #   certManager:
  #     issuerRef:
  #       name: letsencrypt-prod
  #       kind: ClusterIssuer

---
# Auth Secret für Neo4j
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-auth
  namespace: neo4j-cluster
type: Opaque
data:
  # Base64 encoded: neo4j / changeme
  username: bmVvNGo=
  password: Y2hhbmdlbWU=
